name: roberta_binary_reward_model
dataset: null
roberta_kind: roberta-base
freeze_roberta: true
reward_cuttoff: -2
load:
  name: roberta_binary_reward_model
  checkpoint_path: null
  strict_load: true
