defaults:
  - model: bc_lm
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_test
  - evaluator: bc_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  data:
    cache_id: train_raw_data
    cache_path: null
    reward_shift: 0.0
    reward_scale: -5.0
    reward_f:
      name: toxicity_reward
      # name: score_human_reward
      # reddit_path: data/reddit_comments/
      # index_path: data/reddit_comments/train_idxs.json
  max_len: 512
  resample_timeout: 0.0
  include_parent: true

eval_dataset:
  cache_id: d_test
  data:
    cache_id: test_raw_data
    cache_path: null
    reward_shift: 0.0
    reward_scale: -5.0
    reward_f:
      name: toxicity_reward
      # name: score_human_reward
      # reddit_path: data/reddit_comments/
      # index_path: data/reddit_comments/test_idxs.json
  max_len: 512
  resample_timeout: 0.0
  include_parent: true

model:
  transition_weight: 0.0
  dataset:
    name: toxicity_list_dataset
    cache_id: d_train
  load:
    checkpoint_path: null
    strict_load: true

evaluator:
  env:
    reward_shift: 0.0
    reward_scale: -5.0
    data:
      name: reddit_comments
      cache_id: test_raw_data
    reward_f:
      name: toxicity_reward
      # name: model_reward
      # model:
      #   name: roberta_binary_reward_model
      #   dataset:
      #     name: toxicity_list_dataset
      #     cache_id: d_train
      #   roberta_kind: roberta-base
      #   freeze_roberta: false
      #   reward_cuttoff: 0.0
      #   load:
      #     name: roberta_binary_reward_model
      #     checkpoint_path: outputs/toxicity/upvote_reward/model.pkl
      #     strict_load: true
    include_parent: true
  verbose: true
  kind: sample
  generation_kwargs:
    max_generation_len: 256
    num_generations: 1

train:
  save_checkpoint_dir: outputs/toxicity/conditional_toxicity_official_bc_test1/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 0
  bsize: 1
  grad_accum_steps: 64
  log_every: 256
  eval_every: 4096
  save_every: 32768
  max_checkpoints: 1
  eval_bsize: 1
  eval_batches: 32
  lr: 1e-4
  weight_decay: 0.00
  max_steps: null
  loss: {}

wandb:
  use_wandb: true
  wandb_project: toxicity_iql
