defaults:
  - model: bc_lm
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_test
  - evaluator: bc_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  data:
    cache_id: train_raw_data
    cache_path: null
    reward_shift: 0.0
    reward_scale: -5.0
    reward_f:
      # name: bias_reward
      name: score_human_reward
      sentences_path: data/bias_sentences/
      index_path: data/bias_sentences/train_idxs.json
  max_len: 16
  resample_timeout: 0.0
  include_parent: true

eval_dataset:
  cache_id: d_test
  data:
    cache_id: test_raw_data
    cache_path: null
    reward_shift: 0.0
    reward_scale: -5.0
    reward_f:
      # name: bias_reward
      name: score_human_reward
      sentences_path: data/bias_sentences/
      index_path: data/bias_sentences/test_idxs.json
  max_len: 16
  resample_timeout: 0.0
  include_parent: true

model:
  transition_weight: 0.0
  dataset:
    name: bias_list_dataset
    cache_id: d_train
  load:
    checkpoint_path: null
    strict_load: true

evaluator:
  env:
    reward_shift: 0.0
    reward_scale: -5.0
    data:
      name: bias_sentences
      cache_id: test_raw_data
    reward_f:
      # name: bias_reward
      name: model_reward
      model:
        name: roberta_binary_reward_model
        dataset:
          name: bias_list_dataset
          cache_id: d_train
        roberta_kind: roberta-base
        freeze_roberta: false
        reward_cuttoff: -2
        load:
          name: roberta_binary_reward_model
          checkpoint_path: outputs/bias/bias_reward/model.pkl
          strict_load: true
    include_parent: true
  verbose: true
  kind: sample
  generation_kwargs:
    max_generation_len: 1
    num_generations: 1

train:
  save_checkpoint_dir: outputs/bias/conditional_bias_official_bc_test1/
  optim_state_path: null
  epochs: 100
  dataloader_workers: 0
  bsize: 1
  grad_accum_steps: 64
  log_every: 1024
  eval_every: 1024
  save_every: 1024
  max_checkpoints: 1
  eval_bsize: 1
  eval_batches: 16
  lr: 1e-4
  weight_decay: 0.00
  max_steps: null
  loss: {}

wandb:
  use_wandb: false
  wandb_project: bias_iql
