defaults:
  - model: roberta_binary_reward_model
  - dataset@train_dataset: list_test
  - dataset@eval_dataset: list_eval
  - _self_

eval_dataset:
  cache_id: d_eval
  data:
    cache_path: null
    reward_shift: 0.0
    reward_scale: -5.0
    reward_f:
      name: score_human_reward
      sentences_path: data/bias_sentences/
      index_path: data/bias_sentences/eval_idxs.json
  max_len: 16
  cuttoff: null
  resample_timeout: 0.00

train_dataset:
  cache_id: d_test
  data:
    cache_path: null
    reward_shift: 0.0
    reward_scale: -5.0
    reward_f:
      name: score_human_reward
      sentences_path: data/bias_sentences/
      index_path: data/bias_sentences/test_idxs.json
  max_len: 16
  cuttoff: null
  resample_timeout: 0.00

model:
  dataset:
    name: bias_list_dataset
    cache_id: d_test
  roberta_kind: roberta-base
  freeze_roberta: false
  reward_cuttoff: -2
  load:
    checkpoint_path: null
    strict_load: true

evaluator: null

train:
  save_checkpoint_dir: outputs/bias/bias_reward/
  optim_state_path: null
  epochs: 15
  dataloader_workers: 2
  bsize: 16
  grad_accum_steps: 1
  log_every: 16
  eval_every: 16
  save_every: 16
  max_checkpoints: 1
  eval_bsize: 16
  eval_batches: 16
  lr: 1e-5
  weight_decay: 0.00
  max_steps: null
  loss: {}

wandb:
  use_wandb: true
  wandb_project: bias_reward
