defaults:
  - model: per_token_iql
  - dataset: list_val
  - evaluator: vd_iql_evaluator
  - _self_

dataset:
  cache_id: d
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/val_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

model:
  alpha: 0.005
  gamma: 0.99
  beta: 0.0
  transition_weight: 0.0
  clip_weight: null
  value_max: null
  value_min: null
  detach_v: false
  detach_q: false
  detach_pi: false
  double_q: true
  seperate_policy: true
  seperate_target: true
  tau: 0.7
  exp_weights: true
  advanced_mlp: false
  cql_temp: 1.0
  gpt2:
    lm_head: true
    from_pretrained: true
  dataset:
    name: vis_dial_list_dataset
    cache_id: d
  load:
    checkpoint_path: null
    strict_load: true

evaluator:
  env:
    url: http://localhost:5000/step_rank
    actor_stop: false
    dataset:
      name: vis_dial_list_dataset
      cache_id: d
    yn_reward: -2.0
    yn_reward_kind: hard
  verbose: true
  kind: beam
  generation_kwargs:
    max_generation_len: 40
    beam_width: 1
    temp: 1.0
    top_k: null
    top_p: null
    exp_adv: true
    adv_weight: 8.0
    adv_clip: null
    include_logits: true
    include_adv: true
    # num_generations: 1
    # rerank_log_prob_weight: 0.0
    # rerank_advantage_weight: 1.0

eval:
  dataloader_workers: 1
  bsize: 1
  batches: 1024
  print_every: 8
  seed: 0
  log_save_path: null
  loss:
    v_loss_weight: 1.0
    q_loss_weight: 1.0
    awac_weight: 1.0
    cql_loss_weight: 1.0
    mc_returns: false
    
