defaults:
  - model: chai_model
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_val
  - evaluator: chai_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/train_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

eval_dataset:
  cache_id: d_eval
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/val_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

model:
  alpha: 0.005
  gamma: 0.99
  use_cache: true
  cache_path: null
  gpt2:
    lm_head: true
    from_pretrained: true
  dataset:
    name: vis_dial_list_dataset
    cache_id: d_train
  load:
    # (1): train a BC model,
    # (2): run scripts/data/convert_bc.py to convert BC checkpoint to CHAI checkpoint
    # (3): and then replace the checkpoint_path here with the converted BC one
    checkpoint_path: null
    strict_load: true

evaluator:
  env:
    url: http://localhost:5000/step_rank
    actor_stop: false
    dataset:
      name: vis_dial_list_dataset
      cache_id: d_eval
    yn_reward: -2.0
    yn_reward_kind: hard
  verbose: true
  cache_save_path: null
  generation_kwargs:
    max_generation_len: 40
    num_generations: 5
    generation_batches: 1
    temp: 1.0
    top_k: null
    top_p: null

train:
  save_checkpoint_dir: outputs/visual_dialogue/visdial_hard_yn_chai_test1/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 1
  bsize: 4
  grad_accum_steps: 4
  log_every: 256
  eval_every: 1024
  save_every: 32768
  max_checkpoints: 1
  eval_bsize: 16
  eval_batches: 1
  lr: 1e-5
  weight_decay: 0.00
  hard_update_every: null
  max_steps: null
  loss:
    q_loss_weight: 1.0
    v_loss_weight: 0.0
    cql_loss_weight: 0.1
    n_generations: 5
    max_generation_len: null
    temp: 1.0
    top_k: null
    top_p: null
    sample_bsize: 4

wandb:
  use_wandb: true
  wandb_project: visdial_iql
