defaults:
  - model: bc_lm
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_val
  - evaluator: bc_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/train_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

eval_dataset:
  cache_id: d_eval
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/val_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

model:
  transition_weight: 0.0
  dataset:
    name: vis_dial_list_dataset
    cache_id: d_train
  load:
    checkpoint_path: null
    strict_load: true

evaluator:
  env:
    env:
    url: http://localhost:5000/step_rank
    actor_stop: false
    dataset:
      name: vis_dial_list_dataset
      cache_id: d_eval
    yn_reward: -2.0
    yn_reward_kind: hard
  verbose: true
  kind: sample
  generation_kwargs:
    num_generations: 1
    max_generation_len: 40

train:
  save_checkpoint_dir: outputs/visual_dialogue/visdial_bc_test1/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 1
  bsize: 2
  grad_accum_steps: 128
  log_every: 256
  eval_every: 4096
  save_every: 16384
  max_checkpoints: 1
  eval_bsize: 32
  eval_batches: 1
  lr: 1e-4
  weight_decay: 0.00
  max_steps: null
  loss: {}

wandb:
  use_wandb: true
  wandb_project: visdial_iql
