defaults:
  - model: cql_model
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_val
  - evaluator: iql_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/train_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

eval_dataset:
  cache_id: d_eval
  data:
    reward_cache: data/vis_dialogue/processed/visdial_0.5/val_rank_reward_cache1.json
    mode: env_stops
    cutoff_rule:
      name: percentile_cutoff_rule
      goal_value: 1.0
      percentile: 0.5
    yn_reward: -2.0
    yn_reward_kind: hard

model:
  alpha: 0.005
  gamma: 0.99
  beta: 0.0
  transition_weight: 0.0
  clip_weight: null
  value_max: null
  value_min: null
  detach_v: false
  detach_q: false
  detach_pi: false
  double_q: true
  seperate_policy: true
  seperate_target: true
  exp_weights: true
  advanced_mlp: false
  cql_temp: 1.0
  gpt2:
    lm_head: true
    from_pretrained: true
  dataset:
    name: vis_dial_list_dataset
    cache_id: d_train
  load:
    checkpoint_path: null
    strict_load: false

evaluator:
  env:
    url: http://localhost:5000/step_rank
    actor_stop: false
    dataset:
      name: vis_dial_list_dataset
      cache_id: d_eval
    yn_reward: -2.0
    yn_reward_kind: hard
  verbose: true
  kind: sample
  generation_kwargs:
    max_generation_len: 40
    # beam_width: 1
    temp: 1.0
    top_k: null
    top_p: null
    exp_adv: true
    adv_weight: 8.0
    adv_clip: null
    include_logits: true
    include_adv: true
    num_generations: 1
    rerank_log_prob_weight: 0.0
    rerank_advantage_weight: 1.0

train:
  save_checkpoint_dir: outputs/visual_dialogue/visdial_hard_yn_cql_official_test1/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 1
  bsize: 1
  grad_accum_steps: 64
  log_every: 256
  eval_every: 4096
  save_every: 32768
  max_checkpoints: 1
  eval_bsize: 1
  eval_batches: 32
  lr: 1e-4
  weight_decay: 0.00
  hard_update_every: null
  max_steps: null
  loss:
    v_loss_weight: 1.0
    q_loss_weight: 1.0
    awac_weight: 1.0
    cql_loss_weight: 0.1
    dm_loss_weight: 0.0
    mc_returns: false

wandb:
  use_wandb: true
  wandb_project: visdial_iql
